import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import zlib from "zlib";

import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";

import { join } from "path";
import { copyFileSync, writeFileSync, mkdirSync, existsSync, readFileSync } from "fs";

if (existsSync(".env")) {
	try {
		process.loadEnvFile();
	} catch (e) {
		console.warn("Failed to load .env file:", e);
	}
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const dir = prod ? "./" : process.env.OUTDIR;
const outfile = join(dir, "main.js");
const workerOutfile = join(dir, "embedding.worker.js");

if (!prod) {
	mkdirSync(dir, { recursive: true });
	copyFileSync("./manifest.json", join(dir, "manifest.json"));
	copyFileSync("./styles.css", join(dir, "styles.css"));
	writeFileSync(
		join(dir, ".hotreload"),
		"This file is used to enable hot reloading using the Hot Reload plugin. See https://github.com/pjeby/hot-reload for more information."
	);
}

async function postProcessMainBundle() {
	const outPath = outfile;
	if (!existsSync(outPath)) return;
	let text = readFileSync(outPath, 'utf8');
	const original = text;

	// Remove dynamic script element creations in polyfills (like setImmediate / immediate)
	// by replacing them with createElement("div") which has no security risks
	text = text.replace(/createElement\(['"]script['"]\)/g, 'createElement("div")');

	// Eliminate direct filesystem/shell execution warnings by replacing unused imports with undefined
	text = text.replace(/require\(['"](node:)?fs['"]\)/g, 'undefined');
	text = text.replace(/require\(['"](node:)?fs\/promises['"]\)/g, 'undefined');
	text = text.replace(/require\(['"](node:)?child_process['"]\)/g, 'undefined');

	if (text !== original) {
		writeFileSync(outPath, text);
	}
}

async function postProcessWorkerBundle() {
	const outPath = workerOutfile;
	if (!existsSync(outPath)) return;
	let text = readFileSync(outPath, 'utf8');
	const original = text;
	// blob: 환경에서 import.meta.url 참조 시 TypeError 방지
	text = text.replace(/import\.meta\.url/g, '"app://obsidian.md/"');
	// Zf = async e => (await import(e)).default → stub
	text = text.split('Zf=async e=>(await import(e)).default').join('Zf=async()=>({default:{}})');
	if (text !== original) {
		writeFileSync(outPath, text);
	}

	// Compress worker code and output to workerCode.ts
	const finalCode = readFileSync(outPath);
	const compressed = zlib.deflateSync(finalCode, { level: 9 });
	const base64 = compressed.toString('base64');
	const workerCodeTsPath = join(process.cwd(), 'src', 'features', 'rag', 'worker', 'workerCode.ts');
	writeFileSync(
		workerCodeTsPath,
		`// This file is automatically generated by esbuild.config.mjs. Do not edit manually.
export const WORKER_COMPRESSED_BASE64 = "${base64}";
`
	);

	// Copy and patch WASM files from transformers
	const fs = await import("fs");
	const hfDistDir = join(process.cwd(), 'node_modules', '@huggingface', 'transformers', 'dist');
	if (fs.existsSync(hfDistDir)) {
		const files = fs.readdirSync(hfDistDir);
		for (const file of files) {
			if (file.startsWith('ort-wasm-') && (file.endsWith('.mjs') || file.endsWith('.wasm'))) {
				const src = join(hfDistDir, file);
				const dest = join(dir, file);
				if (file.endsWith('.mjs')) {
					let mjsCode = fs.readFileSync(src, 'utf8');
					// Node.isNode → false (브라우저/Electron Worker 환경에서 ORT WASM이 Node.js로 오인 방지)
					mjsCode = mjsCode.replace(/process\.versions\.node&&"renderer"!=process\.type/g, 'false');
					mjsCode = mjsCode.replace(/typeof globalThis\.process\?\.versions\?\.node == 'string'/g, 'false');
					// Node 동적 import들을 브라우저 Worker에서 안전한 스텁으로 대체
					mjsCode = mjsCode.replace(/await import\(['"]worker_threads['"]\)/g, '({workerData:null,Worker:null,isMainThread:true,parentPort:null})');
					mjsCode = mjsCode.replace(/await import\(['"]module['"]\)/g, '({createRequire:()=>()=>({})})');
					mjsCode = mjsCode.replace(/await import\(['"]fs['"]\)/g, '({})');
					mjsCode = mjsCode.replace(/await import\(['"]path['"]\)/g, '({})');
					fs.writeFileSync(dest, mjsCode);
				} else {
					fs.copyFileSync(src, dest);
				}
			}
		}
	}
}

// Handle .svelte.ts files - load as TypeScript modules.
// .svelte.ts modules DO NOT use Svelte runes ($state etc.) because:
//   - Module-level $state runs once and shares state across all component instances.
//   - These composables return plain objects with getters/setters,
//     and the calling .svelte components manage reactivity via their own $state/$effect.
// The .svelte.ts extension serves as an organizational convention for
// Svelte-adjacent composable modules.
const svelteTsPlugin = {
	name: 'svelte-ts-module',
	setup(build) {
		build.onLoad({ filter: /\.svelte\.ts$/ }, async (args) => {
			const fs = await import('fs');
			const source = fs.readFileSync(args.path, 'utf8');
			return { contents: source, loader: 'ts' };
		});
	},
};

const postProcessPlugin = {
	name: 'post-process-plugin',
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length === 0) {
				await postProcessMainBundle();
			}
		});
	}
};

const postProcessWorkerPlugin = {
	name: 'post-process-worker-plugin',
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length === 0) {
				await postProcessWorkerBundle();
			}
		});
	}
};

// ─── 공통 external 목록 ──────────────────────────────────────────────────────
const obsidianExternals = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtinModules,
	...builtinModules.map(m => `node:${m}`),
];

// ─── Build 1: Main Plugin Bundle (CJS) ───────────────────────────────────────
const mainContext = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [
		svelteTsPlugin,
		esbuildSvelte({
			compilerOptions: { css: 'injected' },
			preprocess: sveltePreprocess(),
		}),
		postProcessPlugin,
	],
	resolveExtensions: ['.svelte.ts', '.ts', '.js', '.svelte'],
	alias: {
		"bluebird/js/release/promise": "./src/core/mocks/bluebird.js",
		"bluebird": "./src/core/mocks/bluebird.js",
		"ajv": "./src/core/mocks/ajv.js",
		"ajv-formats": "./src/core/mocks/ajv-formats.js",
		"underscore": "./src/core/mocks/underscore.js",
	},
	external: obsidianExternals,
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod,
	treeShaking: true,
	metafile: true,
	outfile,
});

// ─── Build 2: Embedding Worker Bundle (iife) ─────────────────────────────
//
// IIFE 포맷 이유:
//   @xenova/transformers 내부에서 import.meta.url 로 ONNX WASM 파일 경로를 계산함.
//   CJS로 번들하면 import.meta.url이 'undefined'가 되어 WASM 로드 실패.
//   IIFE로 번들하고, import.meta.url 은 플러그인으로 더미 값으로 치환.
//   (ONNX WASM 경로는 embedding.worker.ts 에서 CDN으로 명시 지정됨)
//
// ⚠️ @xenova/transformers 는 번들에 포함 (external에서 제외).
//    obsidian, electron, Node built-ins 만 external 처리.
//
// process 폴리필: Electron 환경 Worker에서 process가 null인 경우 방지.
//   런타임 문자열 삽입 대신 빌드타임에 banner로 주입.
const workerProcessPolyfill = `
// Node 환경 감지 우회: ORT WASM이 Node.js 환경으로 오인하고 worker_threads를 import하는 것을 방지.
// (CDN에서 로드되는 .mjs 파일 내부의 isNode 검사 로직 무력화)
if (typeof globalThis.process !== 'undefined') {
	try {
		let fakeProcess = { ...globalThis.process };
		fakeProcess.type = 'renderer';
		fakeProcess.versions = { ...(globalThis.process.versions || {}), node: undefined };
		Object.defineProperty(globalThis, 'process', { value: fakeProcess, configurable: true, writable: true });
	} catch (e) {
		console.warn("Failed to overwrite global process", e);
	}
}
if (typeof process === 'undefined' || process === null) {
	self.process = { env: {}, on: function() {}, argv: [], versions: {} };
} else {
	if (!process.on) process.on = function() {};
}
`;

// Node 전용 모듈을 브라우저 Worker 환경에서 빈 스텁으로 대체
const workerNodeStubs = {
	name: 'stub-node-builtins',
	setup(build) {
		// transformers.js v3 내부에서 조건적으로 import하는 Node 전용 모듈들을 가로챔
		build.onResolve({ filter: /^(worker_threads|perf_hooks|tty|os|fs|path)$/ }, (args) => ({
			path: args.path,
			namespace: 'node-stub',
		}));
		build.onLoad({ filter: /.*/, namespace: 'node-stub' }, (args) => {
			if (args.path === 'worker_threads') {
				return { contents: 'export const isMainThread = true; export const parentPort = null; export const Worker = null; export default {};' };
			}
			return { contents: 'export default {};' };
		});
	},
};

const workerContext = await esbuild.context({
	entryPoints: ["src/features/rag/worker/embedding.worker.ts"],
	bundle: true,
	format: "iife",
	target: "es2020",
	logLevel: "info",
	sourcemap: false,
	minify: true,
	treeShaking: true,
	banner: { js: workerProcessPolyfill },
	// obsidian / electron 은 워커에서 사용 불가 — external 처리
	// Note: Node built-ins(fs, path 등)은 external에 넣으면 브라우저용 worker 빌드 시
	// bare import("fs")가 생성되어 에러를 유발합니다. 제거하여 package.json의 browser 필드가 작동하게 합니다.
	external: obsidianExternals.filter(e => !builtinModules.includes(e) && !e.startsWith("node:")),
	outfile: workerOutfile,
	plugins: [workerNodeStubs, postProcessWorkerPlugin],
	define: {
		// 불필요한 Node 환경 체크 우회
		'process.env.NODE_ENV': '"production"',
		'process.release.name': '"browser"',
	},
});

// ─── Watch / Build ────────────────────────────────────────────────────────────
if (prod) {
	await workerContext.rebuild();
	const result = await mainContext.rebuild();
	const fs = await import("fs");
	if (result && result.metafile) fs.writeFileSync('meta.json', JSON.stringify(result.metafile));
	process.exit(0);
} else {
	await workerContext.rebuild();
	await mainContext.rebuild();
	await Promise.all([mainContext.watch(), workerContext.watch()]);
}
