import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";

import { config } from "dotenv";
import { join } from "path";
import { copyFileSync, writeFileSync, mkdirSync } from "fs";

config();

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const dir = prod ? "./" : process.env.OUTDIR;
const outfile = join(dir, "main.js");
const workerOutfile = join(dir, "embedding.worker.js");

if (!prod) {
	mkdirSync(dir, { recursive: true });
	copyFileSync("./manifest.json", join(dir, "manifest.json"));
	copyFileSync("./styles.css", join(dir, "styles.css"));
	writeFileSync(
		join(dir, ".hotreload"),
		"This file is used to enable hot reloading using the Hot Reload plugin. See https://github.com/pjeby/hot-reload for more information."
	);
}

// ─── 공통 external 목록 ──────────────────────────────────────────────────────
const obsidianExternals = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtins,
];

// ─── Build 1: Main Plugin Bundle (CJS) ───────────────────────────────────────
const mainContext = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [
		esbuildSvelte({
			compilerOptions: { css: 'injected' },
			preprocess: sveltePreprocess(),
		}),
	],
	external: obsidianExternals,
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod,
	treeShaking: true,
	outfile,
});

// ─── Build 2: Embedding Worker Bundle (ESM) ───────────────────────────────────
//
// ESM 포맷 이유:
//   @xenova/transformers 내부에서 import.meta.url 로 ONNX WASM 파일 경로를 계산함.
//   CJS로 번들하면 import.meta.url이 'undefined'가 되어 WASM 로드 실패.
//   ESM + metafile 없이 import.meta 보존(preserve) 옵션으로 해결.
//
// ⚠️ @xenova/transformers 는 번들에 포함 (external에서 제외).
//    obsidian, electron, Node built-ins 만 external 처리.
const workerContext = await esbuild.context({
	entryPoints: ["src/features/rag/worker/embedding.worker.ts"],
	bundle: true,
	format: "iife",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod,
	treeShaking: true,
	// obsidian / electron 은 워커에서 사용 불가 — external 처리
	// Note: Node built-ins(fs, path 등)은 external에 넣으면 브라우저용 worker 빌드 시
	// bare import("fs")가 생성되어 에러를 유발합니다. 제거하여 package.json의 browser 필드가 작동하게 합니다.
	external: obsidianExternals.filter(e => !builtins.includes(e)),
	// @xenova/transformers 의 import.meta.url 을 그대로 보존
	// (esbuild 가 번들 시 import.meta.url 을 파일 경로로 교체하지 않도록)
	outfile: workerOutfile,
	define: {
		// 불필요한 Node 환경 체크 우회
		'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
		'process.versions.node': 'undefined',
		'process.release.name': '"browser"',
	},
});

// ─── Watch / Build ────────────────────────────────────────────────────────────

if (prod) {
	await Promise.all([mainContext.rebuild(), workerContext.rebuild()]);
	process.exit(0);
} else {
	// 개발 모드: 둘 다 watch
	await Promise.all([mainContext.watch(), workerContext.watch()]);
}
