/**
 * mocUtils.test.ts
 * buildMocContent 순수 함수 단위 테스트
 */
import { describe, it, expect } from 'vitest';
import { buildMocContent } from './mocUtils';
import type { MocFileEntry } from './mocUtils';

// ── 공통 픽스처 ──────────────────────────────────────────────────────────────

/** 중복 없는 기본 파일 목록 */
const makeFiles = (overrides: Partial<MocFileEntry>[] = []): MocFileEntry[] =>
	overrides.map((o, i) => ({
		path: o.path ?? `folder${i}/note${i}.md`,
		basename: o.basename ?? `note${i}`,
		firstTag: o.firstTag ?? '',
	}));

// ── buildMocContent: 공통 헤더 ────────────────────────────────────────────────

describe('buildMocContent: 헤더', () => {
	it('H1 제목과 날짜 포함 헤더를 생성한다', () => {
		const result = buildMocContent('My MOC', [], 'none', []);
		expect(result).toMatch(/^# My MOC\n/);
		expect(result).toMatch(/> Generated by Lumina on \d{4}-\d{2}-\d{2}/);
	});
});

// ── buildMocContent: 빈 파일 목록 ─────────────────────────────────────────────

describe('buildMocContent: 빈 결과', () => {
	it('파일 목록이 비어있으면 WARNING callout 경고 문구를 포함한다', () => {
		const result = buildMocContent('Empty MOC', [], 'none', []);
		expect(result).toContain('[!WARNING]');
		expect(result).toContain('No notes were found');
	});

	it('빈 결과여도 파일을 생성할 수 있는 마크다운을 반환한다 (빈 MOC 허용)', () => {
		const result = buildMocContent('Empty MOC', [], 'none', []);
		expect(typeof result).toBe('string');
		expect(result.length).toBeGreaterThan(0);
	});
});

// ── buildMocContent: wikilink 중복 체크 ──────────────────────────────────────

describe('buildMocContent: wikilink 형식 (중복 체크)', () => {
	it('basename이 전체 vault에서 유일하면 [[basename]] 형식을 사용한다', () => {
		const files: MocFileEntry[] = [
			{ path: 'Projects/alpha.md', basename: 'alpha', firstTag: '' },
		];
		const allBasenames = ['alpha', 'beta', 'gamma'];
		const result = buildMocContent('Test MOC', files, 'none', allBasenames);
		expect(result).toContain('[[alpha]]');
		expect(result).not.toContain('[[Projects/alpha|alpha]]');
	});

	it('basename이 vault에서 중복되면 [[path/without/ext|basename]] 형식을 사용한다', () => {
		const files: MocFileEntry[] = [
			{ path: 'Projects/alpha.md', basename: 'alpha', firstTag: '' },
		];
		// allBasenames에 alpha가 2개 → 중복
		const allBasenames = ['alpha', 'alpha', 'beta'];
		const result = buildMocContent('Test MOC', files, 'none', allBasenames);
		expect(result).toContain('[[Projects/alpha|alpha]]');
	});

	it('중복 파일이 혼재할 때 unique는 short link, 중복은 full link를 각각 사용한다', () => {
		const files: MocFileEntry[] = [
			{ path: 'A/note.md', basename: 'note', firstTag: '' },
			{ path: 'B/unique.md', basename: 'unique', firstTag: '' },
		];
		// note는 중복, unique는 유일
		const allBasenames = ['note', 'note', 'unique'];
		const result = buildMocContent('Test MOC', files, 'none', allBasenames);
		expect(result).toContain('[[A/note|note]]');
		expect(result).toContain('[[unique]]');
	});
});

// ── buildMocContent: groupBy = 'none' ────────────────────────────────────────

describe('buildMocContent: groupBy = none', () => {
	it('단일 "## Notes" 섹션에 모든 파일을 나열한다', () => {
		const files = makeFiles([
			{ path: 'a.md', basename: 'a' },
			{ path: 'b.md', basename: 'b' },
		]);
		const result = buildMocContent('Test', files, 'none', ['a', 'b']);
		expect(result).toContain('## Notes');
		expect(result).toContain('[[a]]');
		expect(result).toContain('[[b]]');
	});

	it('"folder" 또는 "tag" 섹션 헤딩이 없어야 한다', () => {
		const files = makeFiles([{ path: 'Projects/x.md', basename: 'x' }]);
		const result = buildMocContent('Test', files, 'none', ['x']);
		expect(result).not.toContain('## 📁');
		expect(result).not.toContain('## 🏷️');
	});
});

// ── buildMocContent: groupBy = 'folder' ──────────────────────────────────────

describe('buildMocContent: groupBy = folder', () => {
	it('최상위 폴더별로 섹션이 구분된다', () => {
		const files: MocFileEntry[] = [
			{ path: 'Projects/alpha.md', basename: 'alpha', firstTag: '' },
			{ path: 'Projects/beta.md', basename: 'beta', firstTag: '' },
			{ path: 'Journal/today.md', basename: 'today', firstTag: '' },
		];
		const result = buildMocContent('Test', files, 'folder', ['alpha', 'beta', 'today']);
		expect(result).toContain('## 📁 Projects');
		expect(result).toContain('## 📁 Journal');
		expect(result).toContain('[[alpha]]');
		expect(result).toContain('[[today]]');
	});

	it('루트 파일(폴더 없음)은 "📁 Root" 섹션으로 그룹핑된다', () => {
		const files: MocFileEntry[] = [
			{ path: 'root-note.md', basename: 'root-note', firstTag: '' },
		];
		const result = buildMocContent('Test', files, 'folder', ['root-note']);
		expect(result).toContain('## 📁 Root');
	});

	it('섹션이 알파벳 순으로 정렬된다', () => {
		const files: MocFileEntry[] = [
			{ path: 'Zebra/z.md', basename: 'z', firstTag: '' },
			{ path: 'Apple/a.md', basename: 'a', firstTag: '' },
		];
		const result = buildMocContent('Test', files, 'folder', ['z', 'a']);
		const appleIdx = result.indexOf('## 📁 Apple');
		const zebraIdx = result.indexOf('## 📁 Zebra');
		expect(appleIdx).toBeLessThan(zebraIdx);
	});
});

// ── buildMocContent: groupBy = 'tag' ─────────────────────────────────────────

describe('buildMocContent: groupBy = tag', () => {
	it('첫 번째 태그별로 섹션이 구분된다', () => {
		const files: MocFileEntry[] = [
			{ path: 'a.md', basename: 'a', firstTag: '#project' },
			{ path: 'b.md', basename: 'b', firstTag: '#project' },
			{ path: 'c.md', basename: 'c', firstTag: '#idea' },
		];
		const result = buildMocContent('Test', files, 'tag', ['a', 'b', 'c']);
		expect(result).toContain('## 🏷️ #project');
		expect(result).toContain('## 🏷️ #idea');
		expect(result).toContain('[[a]]');
		expect(result).toContain('[[c]]');
	});

	it('태그 없는 파일은 "🏷️ Untagged" 섹션에 포함된다', () => {
		const files: MocFileEntry[] = [
			{ path: 'no-tag.md', basename: 'no-tag', firstTag: '' },
		];
		const result = buildMocContent('Test', files, 'tag', ['no-tag']);
		expect(result).toContain('## 🏷️ Untagged');
		expect(result).toContain('[[no-tag]]');
	});
});

// ── buildMocContent: 기타 경계 케이스 ────────────────────────────────────────

describe('buildMocContent: 경계 케이스', () => {
	it('파일이 1개여도 정상 출력된다', () => {
		const files: MocFileEntry[] = [
			{ path: 'solo.md', basename: 'solo', firstTag: '' },
		];
		const result = buildMocContent('Solo MOC', files, 'none', ['solo']);
		expect(result).toContain('[[solo]]');
	});

	it('같은 basename이 목록에 있어도 각 항목이 개별 링크로 출력된다', () => {
		const files: MocFileEntry[] = [
			{ path: 'A/note.md', basename: 'note', firstTag: '' },
			{ path: 'B/note.md', basename: 'note', firstTag: '' },
		];
		const allBasenames = ['note', 'note'];
		const result = buildMocContent('Dup Test', files, 'none', allBasenames);
		expect(result).toContain('[[A/note|note]]');
		expect(result).toContain('[[B/note|note]]');
	});

	it('제목에 특수문자가 있어도 H1 헤딩으로 그대로 출력된다', () => {
		const result = buildMocContent('MOC: "Dev & Ops"', [], 'none', []);
		expect(result).toContain('# MOC: "Dev & Ops"');
	});
});
