export type MocGroupBy = 'folder' | 'tag' | 'none';

export interface MocFileEntry {
	/** vault-relative path (e.g. "Projects/note.md") */
	path: string;
	/** file basename without extension (e.g. "note") */
	basename: string;
	/** first tag found in the file (e.g. "#project"), empty string if none */
	firstTag: string;
}

/**
 * 파일명 중복 여부를 검사하여 wikilink 형식을 결정합니다.
 *
 * - basename이 vault 내에서 유일하면 → `[[basename]]`
 * - 중복이 있으면 → `[[path/without/ext|basename]]`
 */
function buildWikilink(entry: MocFileEntry, basenameCount: Map<string, number>): string {
	const pathWithoutExt = entry.path.replace(/\.md$/i, '');
	const count = basenameCount.get(entry.basename) ?? 0;
	if (count <= 1) {
		return `[[${entry.basename}]]`;
	}
	return `[[${pathWithoutExt}|${entry.basename}]]`;
}

/**
 * basename → 등장 횟수 맵을 미리 계산합니다.
 */
function buildBasenameCountMap(files: MocFileEntry[]): Map<string, number> {
	const map = new Map<string, number>();
	for (const f of files) {
		map.set(f.basename, (map.get(f.basename) ?? 0) + 1);
	}
	return map;
}

/**
 * 파일 경로에서 최상위 폴더명을 추출합니다.
 * 루트 파일이면 '/' 를 반환합니다.
 */
function getTopFolder(path: string): string {
	const parts = path.split('/');
	return parts.length > 1 ? parts[0] : '/';
}

const EMPTY_WARNING =
	'> [!WARNING]\n> No notes were found matching the given scope. This MOC is currently empty.\n';

/**
 * MOC 마크다운 콘텐츠를 빌드합니다.
 *
 * @param title      MOC 제목 (H1 헤딩)
 * @param files      수집된 파일 목록
 * @param groupBy    그룹핑 전략
 * @param allBasenames  전체 vault 파일명 목록 (wikilink 중복 판별용)
 * @returns          완성된 마크다운 문자열
 */
export function buildMocContent(
	title: string,
	files: MocFileEntry[],
	groupBy: MocGroupBy,
	allBasenames: string[],
): string {
	const date = new Date().toISOString().split('T')[0];
	const header = `# ${title}\n\n> Generated by Lumina on ${date}\n\n`;

	if (files.length === 0) {
		return header + EMPTY_WARNING;
	}

	// 전체 vault 파일명 기준으로 중복 맵 생성
	const globalBasenameCount = new Map<string, number>();
	for (const name of allBasenames) {
		globalBasenameCount.set(name, (globalBasenameCount.get(name) ?? 0) + 1);
	}

	const sections = buildSections(files, groupBy, globalBasenameCount);

	return header + sections;
}

function buildSections(
	files: MocFileEntry[],
	groupBy: MocGroupBy,
	basenameCount: Map<string, number>,
): string {
	if (groupBy === 'none') {
		const lines = files.map(f => `- ${buildWikilink(f, basenameCount)}`).join('\n');
		return `## Notes\n\n${lines}\n`;
	}

	if (groupBy === 'folder') {
		const groups = new Map<string, MocFileEntry[]>();
		for (const f of files) {
			const key = getTopFolder(f.path);
			if (!groups.has(key)) groups.set(key, []);
			groups.get(key)!.push(f);
		}
		return buildGroupedSections(groups, basenameCount, key => (key === '/' ? '📁 Root' : `📁 ${key}`));
	}

	if (groupBy === 'tag') {
		const groups = new Map<string, MocFileEntry[]>();
		for (const f of files) {
			const key = f.firstTag || 'Untagged';
			if (!groups.has(key)) groups.set(key, []);
			groups.get(key)!.push(f);
		}
		return buildGroupedSections(groups, basenameCount, key =>
			key === 'Untagged' ? '🏷️ Untagged' : `🏷️ ${key}`,
		);
	}

	// fallback: none
	const lines = files.map(f => `- ${buildWikilink(f, basenameCount)}`).join('\n');
	return `## Notes\n\n${lines}\n`;
}

function buildGroupedSections(
	groups: Map<string, MocFileEntry[]>,
	basenameCount: Map<string, number>,
	labelFn: (key: string) => string,
): string {
	const sortedKeys = [...groups.keys()].sort();
	return sortedKeys
		.map(key => {
			const entries = groups.get(key)!;
			const lines = entries.map(f => `- ${buildWikilink(f, basenameCount)}`).join('\n');
			return `## ${labelFn(key)}\n\n${lines}\n`;
		})
		.join('\n');
}
